/**
 * All website content that describes project state or parameters comes from
 * website/data/*.json. These files are generated by `brats-uncertainty export-site-data`
 * from docs/project_status.yaml, configs/protocol/protocol_v1.0.yaml,
 * experiments/EXP-xxx/metadata.yaml and results/index.json. Never edit them by hand.
 */
import statusJson from "../data/status.json";
import protocolJson from "../data/protocol.json";
import experimentsJson from "../data/experiments.json";
import resultsJson from "../data/results.json";

export type GateStatus =
  | "CLOSED"
  | "OWNER_WAIVED"
  | "IN_PROGRESS"
  | "PENDING"
  | "NOT_STARTED"
  | "BLOCKED";

export interface Gate {
  id: string;
  group: string;
  title: string;
  status: GateStatus;
  closed_on: string | null;
}

export interface TimelineItem {
  date: string | null;
  title: string;
  status: string;
}

export interface Status {
  headline: string;
  last_updated: string | null;
  package_version: string;
  protocol: {
    version: string;
    status: string;
    frozen_on: string;
    git_tag: string;
    file: string;
    sha256: string;
  };
  gates: Gate[];
  gate_groups: Record<string, string>;
  next_step: { gate: string; description: string } | null;
  timeline: TimelineItem[];
  project: {
    title: string;
    short_title: string;
    owner: string;
    type: string;
    research_question: string;
    central_question: string;
  };
}

export interface Experiment {
  id: string;
  title: string;
  status: string;
  protocol_sections: string[];
  required_gates: string[];
  notes: string;
}

export interface Results {
  available: boolean;
  statement: string;
  artifacts: unknown[];
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Params = Record<string, any>;

export interface Protocol {
  version: string;
  sha256: string;
  git_tag: string;
  frozen_on: string;
  parameters: Params;
}

export const status = statusJson as unknown as Status;
export const protocol = protocolJson as unknown as Protocol;
export const experiments = (experimentsJson as unknown as { experiments: Experiment[] }).experiments;
export const results = resultsJson as unknown as Results;

/** Optional, non-secret public repository URL used only to build source links. */
export const repoUrl: string | null = process.env.NEXT_PUBLIC_REPO_URL ?? null;

export function sourceLink(path: string): string | null {
  return repoUrl ? `${repoUrl.replace(/\/$/, "")}/blob/main/${path}` : null;
}

export function gateCounts(group: string): { closed: number; total: number } {
  const g = status.gates.filter((x) => x.group === group);
  return {
    closed: g.filter((x) => x.status === "CLOSED" || x.status === "OWNER_WAIVED").length,
    total: g.length,
  };
}
