/**
 * All website content that describes project state or parameters comes from
 * website/data/*.json. These files are generated by `brats-uncertainty export-site-data`
 * from docs/project_status.yaml, configs/protocol/protocol_v1.0.yaml,
 * experiments/EXP-xxx/metadata.yaml and results/index.json. Never edit them by hand.
 */
import statusJson from "../data/status.json";
import protocolJson from "../data/protocol.json";
import experimentsJson from "../data/experiments.json";
import resultsJson from "../data/results.json";
import demoJson from "../data/demo.json";

export type GateStatus =
  | "CLOSED"
  | "OWNER_WAIVED"
  | "IN_PROGRESS"
  | "PENDING"
  | "NOT_STARTED"
  | "BLOCKED"
  | "LOCKED"
  | "AUTHORIZED"
  | "RUNNING"
  | "PASSED"
  | "FAILED";

export interface Gate {
  id: string;
  group: string;
  title: string;
  status: GateStatus;
  closed_on: string | null;
}

export interface TimelineItem {
  date: string | null;
  title: string;
  status: string;
}

export interface OverviewItem {
  key: string;
  label: string;
  status: string;
  /** Exporter-provided label overriding the generic status label (e.g. the B1 basis). */
  status_label?: string;
  detail: string;
}

export interface Amendment {
  id: string;
  type: string;
  date: string;
  title: string;
  file: string;
}

export interface Status {
  headline: string;
  last_updated: string | null;
  package_version: string;
  protocol: {
    version: string;
    status: string;
    frozen_on: string;
    git_tag: string;
    file: string;
    sha256: string;
  };
  gates: Gate[];
  gate_groups: Record<string, string>;
  next_step: { gate: string; description: string } | null;
  timeline: TimelineItem[];
  overview: OverviewItem[];
  count_verification: {
    status: string;
    verification: string;
    label: string;
    targets: Record<string, number>;
    counts?: Record<string, number>;
  };
  data: {
    authorization: string;
    approved_route: string | null;
    acquired: boolean;
    inquiry_sent: boolean;
    statement: string;
    /** Source class of the B1 evidence once B1 has passed; null before. */
    authorization_basis: string | null;
  };
  /** Real-study result status (generated; mirrors results/status.json). */
  results_status: {
    scientific_results_available: boolean;
    real_experiment_executed: boolean;
    real_brats_data_processed: boolean;
    training_status: string;
    status: string;
    synthetic_demo_available: boolean;
  };
  project: {
    title: string;
    short_title: string;
    owner: string;
    type: string;
    research_question: string;
    central_question: string;
  };
}

export interface Experiment {
  id: string;
  title: string;
  status: string;
  protocol_sections: string[];
  required_gates: string[];
  notes: string;
}

export interface Estimate {
  estimate: number;
  ci_low: number;
  ci_high: number;
  p_value_two_sided_approx?: number;
  holm_p?: number;
}

export interface ResultArtifact {
  path: string;
  kind: string;
  name: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  payload: Record<string, any>;
  provenance: { git_commit: string; protocol_sha256: string; generated_at: string };
}

export interface Results {
  available: boolean;
  statement: string;
  artifacts: ResultArtifact[];
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Params = Record<string, any>;

export interface Protocol {
  version: string;
  sha256: string;
  git_tag: string;
  frozen_on: string;
  amendments: Amendment[];
  parameters: Params;
}

export const status = statusJson as unknown as Status;
export const protocol = protocolJson as unknown as Protocol;
export const experiments = (experimentsJson as unknown as { experiments: Experiment[] }).experiments;
export const results = resultsJson as unknown as Results;

/** SYNTHETIC pipeline demonstration (results/demo). Never a scientific result. */
export interface Demo {
  available: boolean;
  demo?: true;
  synthetic?: true;
  scientific_result?: false;
  label?: string;
  disclaimer?: string;
  demo_seed?: number;
  generated_at?: string;
  git_commit?: string;
  bootstrap_replicates?: number;
  synthetic_study?: { validation_cases: number; test_cases: number; conditions: string[] };
  example_primary_statistic?: { name: string; estimate: number; ci_low: number; ci_high: number };
  example_delta_aurc_by_condition?: Record<string, number>;
  example_tau_q?: Record<string, number>;
  example_threshold_transfer_q080?: {
    delta_risk: number;
    delta_coverage: number;
    validation_coverage: number;
    target_coverage: number;
  };
  example_mean_ece_et?: Record<string, number>;
  example_failure_counts?: Record<string, Record<string, number>>;
  figures?: string[];
  artifacts_path?: string;
}

export const demo = demoJson as unknown as Demo;

/** The public repository (clean release). Overridable at build time. */
export const PUBLIC_REPO = "https://github.com/crazykush333/brain-tumor-segmentation-research";

/** Optional, non-secret public repository URL used only to build source links. */
export const repoUrl: string = process.env.NEXT_PUBLIC_REPO_URL ?? PUBLIC_REPO;

export function sourceLink(path: string): string | null {
  return repoUrl ? `${repoUrl.replace(/\/$/, "")}/blob/main/${path}` : null;
}

export function gateCounts(group: string): { closed: number; total: number } {
  const g = status.gates.filter((x) => x.group === group);
  return {
    closed: g.filter((x) => x.status === "CLOSED" || x.status === "OWNER_WAIVED").length,
    total: g.length,
  };
}

/** Status of an overview stage (derived by the exporter from docs/project_status.yaml). */
export function stageStatus(key: string): string {
  return status.overview.find((o) => o.key === key)?.status ?? "UNKNOWN";
}

/** Plain-language facts derived from the status file (never hand-typed on pages). */
export function derivedFacts(): string[] {
  const facts: string[] = [];
  facts.push(status.data.acquired ? "Study data have been acquired." : "No study data have been acquired.");
  const training = stageStatus("training");
  facts.push(training === "NOT_STARTED" ? "No model has been trained." : `Training: ${training.toLowerCase()}.`);
  const split = stageStatus("split");
  facts.push(split === "COMPLETED" ? "The final split has been created." : "No final split has been created.");
  const evaluation = stageStatus("evaluation");
  facts.push(evaluation === "NOT_STARTED" ? "No evaluation has been run." : `Evaluation: ${evaluation.toLowerCase()}.`);
  return facts;
}
