"""Make the guarded trainer classes discoverable by nnU-Net (environment setup step).

nnU-Net finds ``-tr <name>`` by searching the ``nnunetv2.training.nnUNetTrainer``
package. A one-line shim module there re-exports this package's classes; it holds
no logic, so the trainers stay versioned and hashed in this repository.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

SHIM_NAME = "brats_uncertainty_trainers.py"
SHIM_TEXT = (
    '"""Shim generated by brats_uncertainty: re-exports the guarded protocol trainers."""\n'
    "from brats_uncertainty.models.nnunet_trainers import *  # noqa: F403\n"
)


def trainer_package_dir() -> Path | None:
    spec = importlib.util.find_spec("nnunetv2.training.nnUNetTrainer")
    if spec is None or not spec.submodule_search_locations:
        return None
    return Path(next(iter(spec.submodule_search_locations)))


def register_trainers(package_dir: Path | None = None) -> Path:
    """Write (or confirm) the shim; returns its path. Raises if nnU-Net is not installed."""
    target = package_dir or trainer_package_dir()
    if target is None:
        raise ModuleNotFoundError("nnunetv2 is not installed: cannot register the trainers")
    shim = target / SHIM_NAME
    if not shim.is_file() or shim.read_text(encoding="utf-8") != SHIM_TEXT:
        shim.write_text(SHIM_TEXT, encoding="utf-8", newline="\n")
    return shim
